import test from 'node:test';
import assert from 'node:assert/strict';
import {project,validate,History,fill,line,entity,collisionAt} from '../src/model.js';
import {Runtime} from '../src/runtime.js';
test('project round-trip preserves edits and rejects unrelated files',()=>{const p=project(true);p.scenes[0].layers[1].tiles['2,2']=3;assert.deepEqual(validate(JSON.parse(JSON.stringify(p))),p);assert.throws(()=>validate({scenes:[]}));});
test('empty project contains no fictional user content',()=>{const p=project();assert.equal(p.scenes[0].entities.length,0);assert.ok(p.scenes[0].layers.every(l=>Object.keys(l.tiles).length===0));assert.throws(()=>new Runtime(p.scenes[0]),/player spawn/)});
test('undo and redo preserve independent snapshots',()=>{let p=project(),h=new History();h.push(p);p.name='Changed';p=h.undo(p);assert.equal(p.name,'Untitled project');p=h.redo(p);assert.equal(p.name,'Changed');});
test('fill is bounded by terrain and line covers both endpoints',()=>{const map={'1,0':2,'1,1':2,'1,2':2};fill(map,0,0,1,3,3);assert.equal(map['0,2'],1);assert.equal(map['2,0'],undefined);assert.equal(map['1,1'],2);assert.deepEqual(line(0,0,2,2),[[0,0],[1,1],[2,2]]);});
test('collision overrides can remove and add solids',()=>{const s=project().scenes[0];s.layers[1].tiles['1,1']=1;assert.equal(collisionAt(s,1,1),1);s.collision['1,1']=false;assert.equal(collisionAt(s,1,1),0);s.collision['2,2']=true;assert.equal(collisionAt(s,2,2),2);});
function flat(){const s=project().scenes[0];for(let x=0;x<64;x++)s.layers[1].tiles[`${x},10`]=1;s.entities=[entity('player',32,130)];return s;}
test('runtime lands, accelerates, jumps and preserves the editing scene',()=>{const s=flat(),before=JSON.stringify(s),r=new Runtime(s);for(let i=0;i<90;i++)r.update(1/60,new Set());assert.equal(r.player.y,144);assert.ok(r.grounded);for(let i=0;i<20;i++)r.update(1/60,new Set(['ArrowRight']));assert.ok(r.player.x>50);const y=r.player.y;r.update(1/60,new Set([' ']));assert.ok(r.player.y<y);assert.equal(JSON.stringify(s),before);});
test('collectibles score, checkpoints update respawn, doors complete the stage',()=>{const s=flat();s.entities.push(entity('gem',32,144),entity('checkpoint',32,144));const r=new Runtime(s);for(let i=0;i<30;i++)r.update(1/60,new Set());assert.equal(r.score,25);assert.equal(r.spawn.y,144);r.scene.entities.push(entity('door',32,128));r.update(1/60,new Set());assert.ok(r.won);});
test('one-way platforms allow upward travel and stop downward travel',()=>{const s=flat();s.layers[1].tiles['2,7']=4;const r=new Runtime(s);r.player.y=130;r.vy=-300;for(let i=0;i<8;i++)r.update(1/60,new Set([' ']));assert.ok(r.player.y<112);for(let i=0;i<60;i++)r.update(1/60,new Set());assert.equal(r.player.y,96);});
test('falling respawns and pause freezes the simulation',()=>{const r=new Runtime(flat());r.player.y=1000;r.update(1/60,new Set());assert.equal(r.deaths,1);r.paused=true;const before=JSON.stringify(r);r.update(1/60,new Set(['ArrowRight']));assert.equal(JSON.stringify(r),before);});
