import {createRule, eventTypes, actionTypes, gameTypes, biomeNames, entityTypes, validateExtended, clone} from './model.js';
import {buildProjectPackage} from './export.js';
import {templateProject} from './templates.js';

const MARKET_KEY='pixel-forge-marketplace-v1';
const LICENSES=['MIT','Apache-2.0','BSD-2-Clause','GPL-3.0-only'];
const sourceUrl='https://github.com/neshath/omafun';
const $=s=>document.querySelector(s);
const readCatalog=()=>{try{return JSON.parse(localStorage.getItem(MARKET_KEY)||'[]')}catch{return[]}};
const writeCatalog=list=>localStorage.setItem(MARKET_KEY,JSON.stringify(list.slice(0,128)));
const escapeHtml=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

/**
 * The workbench owns the advanced workflows that sit beside the original editor.
 * Marketplace entries are open source package manifests. A package is only
 * published after it includes a license, source URL, author and editable project.
 * Local catalog state is user-owned. Remote catalogs are read-only and are never
 * presented as installed or trusted until the user imports a package.
 */
export function mountWorkbench(api){
 const state={assetFilter:'',tileTransform:{flipX:false,flipY:false,rotation:0},marketSearch:'',marketItems:readCatalog(),marketRemote:[],marketSource:sourceUrl,tutorial:new Set()};
 const style=document.createElement('style');style.textContent='.marketplace{height:calc(100% - 2px);overflow:auto;padding:18px 20px;background:var(--bg)}.market-header{display:flex;justify-content:space-between;gap:18px;align-items:flex-start;border-bottom:1px solid var(--line);padding-bottom:14px}.market-kicker{color:var(--pink);font-size:9px;letter-spacing:1.4px}.market-header h2{font-size:19px;margin:5px 0}.market-header p{font-size:10px}.market-primary{background:var(--pink);color:white;border-color:var(--pink)}.market-controls{display:grid;grid-template-columns:minmax(150px,1fr) minmax(160px,1fr) auto;gap:8px;margin:14px 0}.market-controls input{font-size:10px;padding:6px}.market-controls button{font-size:10px}.market-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(190px,1fr));gap:10px}.market-card{border:1px solid var(--line);background:var(--panel);padding:12px;min-height:140px;display:flex;flex-direction:column}.market-card-top,.market-meta{display:flex;justify-content:space-between;color:var(--muted);font-size:8px}.market-card-top span:first-child{color:var(--cyan);letter-spacing:1px}.market-card h3{margin:10px 0 4px;font-size:13px}.market-card p{font-size:10px;line-height:1.5;flex:1}.market-actions{display:flex;justify-content:space-between;align-items:center;margin-top:10px}.market-actions button,.market-actions a{font-size:9px;padding:5px 7px;border:1px solid var(--line);color:var(--ink);text-decoration:none}.market-actions a{border:0;color:var(--cyan)}.market-empty{border:1px dashed var(--line);padding:28px;display:flex;flex-direction:column;gap:8px;color:var(--muted);grid-column:1/-1}.market-empty strong{color:var(--ink)}.market-notice{color:var(--muted);font-size:9px;margin-top:14px}.market-field{display:flex;align-items:center;justify-content:space-between;gap:10px;margin:8px 0;font-size:9px}.market-field input,.market-field select{width:58%;padding:5px;font-size:9px}.logic-panel{padding:12px;overflow:auto}.logic-list{display:flex;flex-direction:column;gap:7px}.logic-row{display:grid;grid-template-columns:1.1fr 1fr 1fr 1fr auto;gap:5px;align-items:end;padding:7px;background:var(--bg);border:1px solid var(--line)}.logic-row button{padding:5px}.high-contrast{--muted:oklch(.86 .02 285);--line:oklch(.52 .02 285)}';document.head.append(style);
 const tabs=document.querySelector('.asset-tabs');
 for(const [id,label] of [['logic','⌘ Logic'],['market','✦ Market']]){if(!tabs?.querySelector(`[data-tab="${id}"]`)){const button=document.createElement('button');button.dataset.tab=id;button.textContent=label;button.onclick=()=>api.setTab(id);tabs?.insertBefore(button,document.querySelector('#collapse'));}}
 const refreshMarket=()=>{state.marketItems=readCatalog();};
 const makeInput=(label,value,onChange,type='text')=>{const wrap=document.createElement('label');wrap.className='market-field';const span=document.createElement('span');span.textContent=label;const input=document.createElement('input');input.type=type;input.value=value??'';input.onchange=()=>onChange(input.value);wrap.append(span,input);return wrap};
 const makeSelect=(label,value,options,onChange)=>{const wrap=document.createElement('label');wrap.className='market-field';const span=document.createElement('span');span.textContent=label;const select=document.createElement('select');options.forEach(([v,t])=>{const o=document.createElement('option');o.value=v;o.textContent=t;select.append(o)});select.value=value;select.onchange=()=>onChange(select.value);wrap.append(span,select);return wrap};
 const setStatus=message=>api.note(message);
 const downloadPackage=()=>{
  const p=clone(api.project);p.license??='MIT';p.sourceUrl??=sourceUrl;p.author??='Local creator';p.description??='An editable Pixel Forge game.';p.marketplace={openSource:true,license:p.license,sourceUrl:p.sourceUrl,author:p.author,description:p.description,version:'0.1.0'};
  if(!LICENSES.includes(p.license)||!/^https:\/\//.test(p.sourceUrl)||!p.author.trim()){setStatus('Add a license, https source URL, and author before sharing.');return;}
  const manifest={id:p.id,name:p.name,version:p.marketplace.version,description:p.marketplace.description,author:p.author,license:p.license,sourceUrl:p.sourceUrl,openSource:true,updatedAt:Date.now(),package:p};
  const list=readCatalog().filter(x=>x.id!==manifest.id);list.unshift(manifest);writeCatalog(list);state.marketItems=list;
  api.download(JSON.stringify(manifest,null,2),p.name.replace(/[^a-z0-9]+/gi,'-').toLowerCase()+'.pixel-market.json','application/json');setStatus('Open-source package exported and added to your local marketplace.');state.tutorial.add('share');renderMarket();
 };
 const importPackage=async file=>{try{if(file.size>20_000_000)throw Error('Package is larger than 20 MB.');const manifest=JSON.parse(await file.text());if(manifest.openSource!==true||!LICENSES.includes(manifest.license)||!manifest.sourceUrl||!manifest.package)throw Error('This package is missing its open-source license or source.');const checked=validateExtended(manifest.package);const safe={...manifest,package:checked};const list=readCatalog().filter(x=>x.id!==safe.id);list.unshift(safe);writeCatalog(list);state.marketItems=list;renderMarket();setStatus(`Imported ${safe.name}. It remains editable and open source.`);}catch(error){setStatus('Import failed: '+error.message);}};
 const remoteCatalog=async()=>{try{setStatus('Reading the public catalog…');const r=await fetch(state.marketSource,{cache:'no-store'});if(!r.ok)throw Error(`Catalog returned ${r.status}`);const data=await r.json();if(!Array.isArray(data))throw Error('Catalog must be a JSON array.');state.marketRemote=data.filter(x=>x.openSource===true&&x.license&&x.sourceUrl);renderMarket();setStatus(`${state.marketRemote.length} open-source games found in the public catalog.`);}catch(error){setStatus('Could not read remote catalog: '+error.message);}};
 const createRuleUI=()=>{
  const s=api.scene;const list=s.events??=[];const host=document.createElement('div');host.className='logic-list';
  list.forEach((rule,index)=>{const row=document.createElement('div');row.className='logic-row';row.append(makeInput('Name',rule.name,v=>{api.checkpoint();rule.name=v;api.changed()}),makeSelect('When',rule.event,Object.entries(eventTypes),v=>{api.checkpoint();rule.event=v;api.changed()}),makeSelect('Do',rule.action,Object.entries(actionTypes),v=>{api.checkpoint();rule.action=v;api.changed()}),makeInput('Target',rule.targetId||'*',v=>{api.checkpoint();rule.targetId=v;api.changed()},'text'));const del=document.createElement('button');del.textContent='×';del.onclick=()=>{api.checkpoint();s.events.splice(index,1);api.changed();renderAssets('logic')};row.append(del);host.append(row)});const add=document.createElement('button');add.textContent='＋ Add rule';add.onclick=()=>{api.checkpoint();s.events.push(createRule());api.changed();renderAssets('logic')};host.append(add);return host;};
 const renderMarket=()=>{const host=$('#assets');if(!host)return true;$('.asset-filters').hidden=true;host.className='marketplace';host.replaceChildren();const head=document.createElement('div');head.className='market-header';head.innerHTML='<div><span class="market-kicker">OPEN SOURCE EXCHANGE</span><h2>Find a world. Fork its rules.</h2><p>Every listing includes editable project data, a license, and a source link.</p></div>';const importBtn=document.createElement('button');importBtn.textContent='↑ Import package';const file=document.createElement('input');file.type='file';file.accept='.pixel-market.json,application/json';file.hidden=true;file.onchange=()=>file.files[0]&&importPackage(file.files[0]);importBtn.onclick=()=>file.click();const share=document.createElement('button');share.className='market-primary';share.textContent='↓ Share this game';share.onclick=downloadPackage;head.append(importBtn,share,file);host.append(head);
  const controls=document.createElement('div');controls.className='market-controls';const search=document.createElement('input');search.placeholder='Search public and local games…';search.value=state.marketSearch;search.oninput=()=>{state.marketSearch=search.value;renderMarket()};const source=document.createElement('input');source.value=state.marketSource;source.title='Read-only catalog URL';const refresh=document.createElement('button');refresh.textContent='↻ Refresh catalog';refresh.onclick=()=>{state.marketSource=source.value;remoteCatalog()};controls.append(search,source,refresh);host.append(controls);
  const all=[...state.marketRemote.map(x=>({...x,origin:'PUBLIC'})),...state.marketItems.map(x=>({...x,origin:'LOCAL'}))].filter((x,i,a)=>a.findIndex(y=>y.id===x.id)===i).filter(x=>`${x.name} ${x.description} ${x.author}`.toLowerCase().includes(state.marketSearch.toLowerCase()));const grid=document.createElement('div');grid.className='market-grid';if(!all.length){const empty=document.createElement('div');empty.className='market-empty';empty.innerHTML='<strong>Your exchange is empty.</strong><span>Import an open-source .pixel-market.json package, or share the game you are editing.</span>';grid.append(empty)}all.forEach(item=>{const card=document.createElement('article');card.className='market-card';card.innerHTML=`<div class="market-card-top"><span>${escapeHtml(item.origin)}</span><span>♡</span></div><h3>${escapeHtml(item.name)}</h3><p>${escapeHtml(item.description||'Editable Pixel Forge project.')}</p><div class="market-meta"><span>${escapeHtml(item.author||'Unknown author')}</span><span>${escapeHtml(item.license||'License missing')}</span></div>`;const actions=document.createElement('div');actions.className='market-actions';if(item.package){const open=document.createElement('button');open.textContent='Open / fork';open.onclick=()=>{api.loadProject(item.package);setStatus(`Opened ${item.name}. Make it yours and keep the source link.`)};actions.append(open)}const link=document.createElement('a');link.href=item.sourceUrl;link.target='_blank';link.rel='noreferrer';link.textContent='View source ↗';actions.append(link);card.append(actions);grid.append(card)});host.append(grid);const info=document.createElement('div');info.className='market-notice';info.textContent='Marketplace sharing is file-based and transparent: source code stays with the package, licenses are required, and remote catalogs are read-only.';host.append(info);return true;};
 const renderSettings=()=>{const host=$('#inspection');host.replaceChildren();const title=document.createElement('div');title.className='inspect-title';title.innerHTML='<div><strong>PROJECT SETTINGS</strong><small>FORMAT, ACCESSIBILITY, RULES</small></div>';host.append(title);const sec=document.createElement('div');sec.className='inspect-section';sec.append(makeSelect('Game format',api.scene.gameType,Object.entries(gameTypes),v=>{api.checkpoint();api.scene.gameType=v;api.changed();api.refresh()}),makeSelect('World palette',api.scene.biome,Object.entries(biomeNames),v=>{api.checkpoint();api.scene.biome=v;api.changed();api.refresh()}),makeInput('Objective',api.scene.hud.objective,v=>{api.checkpoint();api.scene.hud.objective=v;api.changed()}));host.append(sec);const access=document.createElement('div');access.className='inspect-section';access.innerHTML='<h3>ACCESSIBILITY</h3>';const p=api.project;p.settings??={};const high=makeInput('High contrast',p.settings.highContrast?'on':'off',v=>{p.settings.highContrast=v==='on';document.body.classList.toggle('high-contrast',p.settings.highContrast);api.changed()});const reduced=makeInput('Reduced motion',p.settings.reducedMotion?'on':'off',v=>{p.settings.reducedMotion=v==='on';api.changed()});access.append(high,reduced);host.append(access);const rules=document.createElement('div');rules.className='inspect-section';rules.append(Object.assign(document.createElement('h3'),{textContent:'EVENT LOGIC'}),createRuleUI());host.append(rules);return true;};
 return {assetFilter:(a,tab)=>tab!=='tiles'||a.id<=18,renderAssets(tab){if(tab==='market')return renderMarket();if(tab==='logic'){$('#assets').className='logic-panel';$('#assets').replaceChildren(createRuleUI());$('.asset-filters').hidden=true;return true}return false},renderInspector(){return false},refresh(){},restorePalette(){},syncSprite(){},pointerDown(){return false},pointerMove(){},pointerUp(){},drawOverlay(){},keyDown(){return false},touchAsset(){},completeTutorial(){},renderMarket,renderSettings,importPackage};
}
